// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJothl-nBVsGLcvMNaDtcBO9hdQPFC_es',
    appId: '1:1025925028604:web:63c7d41953a2423a051579',
    messagingSenderId: '1025925028604',
    projectId: 'my-app-be9a4',
    authDomain: 'my-app-be9a4.firebaseapp.com',
    storageBucket: 'my-app-be9a4.firebasestorage.app',
    measurementId: 'G-4EYCTFVK72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ZHsB6-msfKMZRValhAx_pDDMfyYfaDg',
    appId: '1:1025925028604:android:bf362c90db2f35ee051579',
    messagingSenderId: '1025925028604',
    projectId: 'my-app-be9a4',
    storageBucket: 'my-app-be9a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0es7mwQfEJ3Hjw6NMlVgpo-yFnNgIRT8',
    appId: '1:1025925028604:ios:fdcf1f3e7d42a9e0051579',
    messagingSenderId: '1025925028604',
    projectId: 'my-app-be9a4',
    storageBucket: 'my-app-be9a4.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0es7mwQfEJ3Hjw6NMlVgpo-yFnNgIRT8',
    appId: '1:1025925028604:ios:fdcf1f3e7d42a9e0051579',
    messagingSenderId: '1025925028604',
    projectId: 'my-app-be9a4',
    storageBucket: 'my-app-be9a4.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJothl-nBVsGLcvMNaDtcBO9hdQPFC_es',
    appId: '1:1025925028604:web:1c33f25ebc85d6e3051579',
    messagingSenderId: '1025925028604',
    projectId: 'my-app-be9a4',
    authDomain: 'my-app-be9a4.firebaseapp.com',
    storageBucket: 'my-app-be9a4.firebasestorage.app',
    measurementId: 'G-T78DDGEYD3',
  );
}
